"""
Central, single-source-of-truth scenario / model parameters for the demand pipeline.

AUTO-GENERATED by run_full_pipeline.ipynb on 2026-09-02T16:39:51.
Edit PARAMS in that notebook and re-run it to regenerate this file - manual edits
here will be overwritten on the next pipeline run.
"""

BASE_INTENSITY = {
    '0-1945': 250,
    '1946-1969': 230,
    '1970-1979': 170,
    '1980-1989': 135,
    '1990-1999': 110,
    '2000-2010': 85,
    '2011-2020': 50,
    'post-2020': 35,
}

DEMOLITION_RATE = {
    '0-1945': 0.003,
    '1946-1969': 0.002,
    '1970-1979': 0.001,
    '1980-1989': 0.0005,
    '1990-1999': 0.0,
    '2000-2010': 0.0,
    '2011-2020': 0.0,
    'post-2020': 0.0,
}

RENOVATION_DEPTH = 0.35

RENOVATION_START = 0.01

HIST_RENOVATION_RATE = 0.0

SCENARIO_RENOVATION = {
    'KKO': 0.02,
    'KVE': 0.015,
    'VWE': 0.015,
    'VNI': 0.01,
}

EPSILON_DEFAULT = 0.25

EPSILON_BOUNDS = (0.05, 0.6)

PERMIT_LAG = 1

HP_SCENARIOS = {
    'KKO': {'target_year': 2050, 'target_fraction': 0.9},
    'KVE': {'target_year': 2055, 'target_fraction': 0.9},
    'VWE': {'target_year': 2060, 'target_fraction': 0.9},
    'VNI': {'target_year': 2060, 'target_fraction': 0.75},
}

USE_DYNAMIC_COP = True

COP_ALPHA = 0.3

THERMAL_REF = 150

COP_MAX = 6.5

SERVICE_MULTIPLIER = 1

COP_MAP = {
    'Austria': 4.0,
    'Belgium': 4.0,
    'Bulgaria': 3.5,
    'Croatia': 4.3,
    'Czechia': 3.5,
    'Denmark': 3.3,
    'Estonia': 3.3,
    'Finland': 3.3,
    'France': 4.0,
    'Germany': 4.0,
    'Greece': 4.3,
    'Hungary': 3.5,
    'Ireland': 4.0,
    'Italy': 4.0,
    'Latvia': 3.3,
    'Lithuania': 3.3,
    'Luxembourg': 4.0,
    'Netherlands': 4.0,
    'Norway': 3.3,
    'Poland': 3.5,
    'Portugal': 4.3,
    'Romania': 3.5,
    'Slovakia': 3.5,
    'Slovenia': 4.3,
    'Spain': 4.3,
    'Sweden': 3.3,
}

USE_HDD_CDD_SCENARIOS = True

CLIMATE_SCENARIO_MAP = {
    'KKO': 'SSP1',
    'KVE': 'SSP2',
    'VWE': 'SSP5',
    'VNI': 'SSP3',
}

FLOOR_BASELINE_SCENARIO = 'KKO'
